// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxschedule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * schedules microflow by cron
 * returns true on success, false on fail
 */
public class ja_putSchedule_mf_cron extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String str_mf;
	private java.lang.String str_cron;

	public ja_putSchedule_mf_cron(IContext context, java.lang.String str_mf, java.lang.String str_cron)
	{
		super(context);
		this.str_mf = str_mf;
		this.str_cron = str_cron;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.lang.Boolean ret=false;
		if(str_mf==null){
			throw new java.lang.Exception("Microflow null:Aborting...");
		}
		if(str_cron==null){
			throw new java.lang.Exception("Cron null:Aborting...");
		}
		org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler scheduler = new org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler();
		scheduler.initialize();
		scheduler.schedule(
			new java.lang.Runnable() {
				@Override
				public void run() {
					try{
						com.mendix.core.Core.execute(
							com.mendix.core.Core.createSystemContext(),
							str_mf,
							true,
							null
						);
					}catch(Exception e){
						com.mendix.core.Core.getLogger("Runnable").error(e.toString());
					}
				}
			},
			new org.springframework.scheduling.support.CronTrigger(str_cron)
		);
		mxschedule.Schedule.hashmap.put(java.util.UUID.randomUUID().toString(),scheduler);
		ret=true;
		return ret;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ja_putSchedule_mf_cron";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
