// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxschedule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * schedules microflow by cron
 * returns true on success, false on fail
 */
public class ja_putSchedule_mf_cron extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String str_mf;
	private java.lang.String str_cron;

	public ja_putSchedule_mf_cron(IContext context, java.lang.String str_mf, java.lang.String str_cron)
	{
		super(context);
		this.str_mf = str_mf;
		this.str_cron = str_cron;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ja_putSchedule_mf_cron";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
