// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datanp.proxies;

public class FileDocument extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataNP.FileDocument";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		FileDocument_FileDocument_1("DataNP.FileDocument_FileDocument_1"),
		FileDocument_FileDocument_2("DataNP.FileDocument_FileDocument_2");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FileDocument(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DataNP.FileDocument"));
	}

	protected FileDocument(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fileDocumentMendixObject)
	{
		super(context, fileDocumentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DataNP.FileDocument", fileDocumentMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DataNP.FileDocument");
	}

	/**
	 * @deprecated Use 'FileDocument.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static datanp.proxies.FileDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return datanp.proxies.FileDocument.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static datanp.proxies.FileDocument initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new datanp.proxies.FileDocument(context, mendixObject);
	}

	public static datanp.proxies.FileDocument load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return datanp.proxies.FileDocument.initialize(context, mendixObject);
	}

	public static java.util.List<datanp.proxies.FileDocument> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<datanp.proxies.FileDocument> result = new java.util.ArrayList<datanp.proxies.FileDocument>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//DataNP.FileDocument" + xpathConstraint))
			result.add(datanp.proxies.FileDocument.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of FileDocument_FileDocument_1
	 */
	public final datanp.proxies.FileDocument getFileDocument_FileDocument_1() throws com.mendix.core.CoreException
	{
		return getFileDocument_FileDocument_1(getContext());
	}

	/**
	 * @param context
	 * @return value of FileDocument_FileDocument_1
	 */
	public final datanp.proxies.FileDocument getFileDocument_FileDocument_1(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		datanp.proxies.FileDocument result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FileDocument_FileDocument_1.toString());
		if (identifier != null)
			result = datanp.proxies.FileDocument.load(context, identifier);
		return result;
	}

	/**
	 * Set value of FileDocument_FileDocument_1
	 * @param filedocument_filedocument_1
	 */
	public final void setFileDocument_FileDocument_1(datanp.proxies.FileDocument filedocument_filedocument_1)
	{
		setFileDocument_FileDocument_1(getContext(), filedocument_filedocument_1);
	}

	/**
	 * Set value of FileDocument_FileDocument_1
	 * @param context
	 * @param filedocument_filedocument_1
	 */
	public final void setFileDocument_FileDocument_1(com.mendix.systemwideinterfaces.core.IContext context, datanp.proxies.FileDocument filedocument_filedocument_1)
	{
		if (filedocument_filedocument_1 == null)
			getMendixObject().setValue(context, MemberNames.FileDocument_FileDocument_1.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.FileDocument_FileDocument_1.toString(), filedocument_filedocument_1.getMendixObject().getId());
	}

	/**
	 * @return value of FileDocument_FileDocument_2
	 */
	public final java.util.List<datanp.proxies.FileDocument> getFileDocument_FileDocument_2() throws com.mendix.core.CoreException
	{
		return getFileDocument_FileDocument_2(getContext());
	}

	/**
	 * @param context
	 * @return value of FileDocument_FileDocument_2
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<datanp.proxies.FileDocument> getFileDocument_FileDocument_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<datanp.proxies.FileDocument> result = new java.util.ArrayList<datanp.proxies.FileDocument>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.FileDocument_FileDocument_2.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(datanp.proxies.FileDocument.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of FileDocument_FileDocument_2
	 * @param filedocument_filedocument_2
	 */
	public final void setFileDocument_FileDocument_2(java.util.List<datanp.proxies.FileDocument> filedocument_filedocument_2)
	{
		setFileDocument_FileDocument_2(getContext(), filedocument_filedocument_2);
	}

	/**
	 * Set value of FileDocument_FileDocument_2
	 * @param context
	 * @param filedocument_filedocument_2
	 */
	public final void setFileDocument_FileDocument_2(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<datanp.proxies.FileDocument> filedocument_filedocument_2)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (datanp.proxies.FileDocument proxyObject : filedocument_filedocument_2)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.FileDocument_FileDocument_2.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final datanp.proxies.FileDocument that = (datanp.proxies.FileDocument) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DataNP.FileDocument";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
