// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datanp.proxies;

public class Vec2f extends datanp.proxies.Vec1f
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataNP.Vec2f";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_1("_1"),
		_0("_0"),
		idx("idx"),
		Data_Data_0("DataNP.Data_Data_0"),
		Data_Data_1("DataNP.Data_Data_1"),
		Data_FileDocument_1("DataNP.Data_FileDocument_1"),
		Data_FileDocument_2("DataNP.Data_FileDocument_2"),
		Data_Session("DataNP.Data_Session");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Vec2f(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DataNP.Vec2f"));
	}

	protected Vec2f(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject vec2fMendixObject)
	{
		super(context, vec2fMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DataNP.Vec2f", vec2fMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DataNP.Vec2f");
	}

	/**
	 * @deprecated Use 'Vec2f.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static datanp.proxies.Vec2f initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return datanp.proxies.Vec2f.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static datanp.proxies.Vec2f initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("DataNP.Vec3f", mendixObject.getType()))
			return datanp.proxies.Vec3f.initialize(context, mendixObject);

		return new datanp.proxies.Vec2f(context, mendixObject);
	}

	public static datanp.proxies.Vec2f load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return datanp.proxies.Vec2f.initialize(context, mendixObject);
	}

	/**
	 * @return value of _1
	 */
	public final java.lang.Double get_1()
	{
		return get_1(getContext());
	}

	/**
	 * @param context
	 * @return value of _1
	 */
	public final java.lang.Double get_1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Double) getMendixObject().getValue(context, MemberNames._1.toString());
	}

	/**
	 * Set value of _1
	 * @param _1
	 */
	public final void set_1(java.lang.Double _1)
	{
		set_1(getContext(), _1);
	}

	/**
	 * Set value of _1
	 * @param context
	 * @param _1
	 */
	public final void set_1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Double _1)
	{
		getMendixObject().setValue(context, MemberNames._1.toString(), _1);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final datanp.proxies.Vec2f that = (datanp.proxies.Vec2f) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DataNP.Vec2f";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
