// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datanp.proxies;

public class Vec4s extends datanp.proxies.Vec3s
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DataNP.Vec4s";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_3("_3"),
		_2("_2"),
		_1("_1"),
		_0("_0"),
		idx("idx"),
		Data_Data_0("DataNP.Data_Data_0"),
		Data_Data_1("DataNP.Data_Data_1"),
		Data_FileDocument_1("DataNP.Data_FileDocument_1"),
		Data_FileDocument_2("DataNP.Data_FileDocument_2"),
		Data_Session("DataNP.Data_Session");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Vec4s(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "DataNP.Vec4s"));
	}

	protected Vec4s(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject vec4sMendixObject)
	{
		super(context, vec4sMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("DataNP.Vec4s", vec4sMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a DataNP.Vec4s");
	}

	/**
	 * @deprecated Use 'Vec4s.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static datanp.proxies.Vec4s initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return datanp.proxies.Vec4s.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static datanp.proxies.Vec4s initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new datanp.proxies.Vec4s(context, mendixObject);
	}

	public static datanp.proxies.Vec4s load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return datanp.proxies.Vec4s.initialize(context, mendixObject);
	}

	/**
	 * @return value of _3
	 */
	public final java.lang.String get_3()
	{
		return get_3(getContext());
	}

	/**
	 * @param context
	 * @return value of _3
	 */
	public final java.lang.String get_3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._3.toString());
	}

	/**
	 * Set value of _3
	 * @param _3
	 */
	public final void set_3(java.lang.String _3)
	{
		set_3(getContext(), _3);
	}

	/**
	 * Set value of _3
	 * @param context
	 * @param _3
	 */
	public final void set_3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _3)
	{
		getMendixObject().setValue(context, MemberNames._3.toString(), _3);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final datanp.proxies.Vec4s that = (datanp.proxies.Vec4s) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "DataNP.Vec4s";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
