// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxschedule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * gets a scheduled action by searching the global mxutil.Schedule hashmap by key, shuts down the schedule, and removes the hashmap entry
 * 
 * returns true if eleted, false if not delted
 */
public class ja_deleteSchedule extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String str_k;

	public ja_deleteSchedule(IContext context, java.lang.String str_k)
	{
		super(context);
		this.str_k = str_k;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		java.lang.Boolean ret=false;
		if(str_k!=null){
			org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler tpts=(org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler)mxschedule.Schedule.hashmap.get(str_k);
			if(tpts!=null)
				tpts.shutdown();
			mxschedule.Schedule.hashmap.remove(str_k);
			ret=true;
		}else{
			com.mendix.core.Core.getLogger(this.toString()).error("Key null:Aborting...");
			ret=false;
		}
		return ret;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ja_deleteSchedule";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
